TEMP
ePages-de/react-components pull request #21
Opened 2016-11-01 11:03 UTC by choffmeister

2016-11-01 15:21 UTC, choffmeister commented
@erikmueller Might want to take a look?

2016-11-02 10:56 UTC, erikmueller requested changes

2016-11-02 10:56 UTC, erikmueller commented on src/form/SortField.jsx
>      const self = this
kill your `self`

2016-11-02 10:56 UTC, erikmueller commented on src/form/formField.jsx
> +        wrappedComponent && ['focus'].forEach((methodName) => {
please just hoist 'focus' the right way. No need to hoist sth else later

2016-11-02 12:15 UTC, erikmueller approved these changes

2016-11-02 12:16 UTC, merged