Epng 3494 add async validation to form
ePages-de/react-components pull request #35
Opened 2018-04-03 15:30 UTC by asandau

This is probably not up to your standards. But it seems to work :D
Please review and give suggestions on how to improve. Thanks

2018-04-06 11:42 UTC, ingmarh requested changes
Nice addition!

I was thinking about if we can have the "Promise linearization" without (the copied into) `createPromiseLinearizer` function.

I was also thinking about the API additions: Instead of a new `validateAsync`, I'd prefer to extend the existing `validate` prop handling with async support and have the new `validateAsyncWaitMs` prop renamed to `validateWaitMs`.

Something like this:

```jsx
function createLinearizedDebouncedFunc (func, waitMs = 0) {
  let timer = null

  return (...args) => {
    return new Promise(resolve => {
      if (timer) window.clearTimeout(timer)
      timer = window.setTimeout(() => {
        timer = null
        resolve(func(...args))
      }, waitMs)
    })
  }
}

export default class Form extends React.Component {
  static propTypes = {
    // ...    
    validateWaitMs: PropTypes.number,
  }

  static defaultProps = {
    // ...
    validateWaitMs: 0,
  }

  constructor (props) {
    super(props)

    // supports `props.validate(value, forSubmit): object | Promise<object>`
    this.validate = createLinearizedDebouncedFunc(props.validate, props.validateWaitMs)
  }

  setValue = (name, value) => {
    // ...
    const newValue = newValue2 || newValue1

    this.setState({ value: newValue })

    this.validate(newValue, this.state.triedToSubmit)
      .then(errors => {
        this.setState({
          errors: containsError(errors) ? errors : new Immutable.Map()
        })
      })
  }

  onSubmit = (event) => {
    if (!this.props.disabled && !this.state.submitting) {
      this.validate(this.state.value, true)
        .then(errors => {
          // ...
        })
    }
  }
}
```

With that, `props.validate` would support a return value of either an object (like it is currently) or a `Promise` resolving with an object. Internally, `this.validate` would always be handled asynchronously and return a `Promise`.

I would like to talk about this in person and try it out together.

(Also, this would need to have new tests in "Form.spec.jsx".)

2018-04-06 11:42 UTC, ingmarh commented on src/form/Form.jsx
> +  handleAsyncValidate = (value, changedFiled, triedToSubmit) => {
For what is this new argument, `changedFiled`, supposed to be used?

2018-04-06 11:42 UTC, ingmarh commented on src/form/Form.jsx
> +    const {name, value, onSubmit, onChange, prepare, validate, validateAsync, validateAsyncWaitMs, normalize, disabled, children, ...other} = this.props // eslint-disable-line no-unused-vars
Instead of the comment at the end of this line, please use `// eslint-disable-next-line no-unused-vars` one line above.

2018-04-06 12:34 UTC, ingmarh commented on src/form/Form.jsx
> +  handleAsyncValidate = (value, changedFiled, triedToSubmit) => {
Okay, now I see why you added this. If we end up extending `props.validate` to add async support, then I propose to switch the argument order to be `(value, forSubmit, changedField)` for backwards compatibility.

2018-04-06 13:38 UTC, Raigen requested changes

2018-04-06 13:38 UTC, Raigen commented on src/form/Form.jsx
> +        resolve(this.props.validate(value, triedToSubmit))
You can simply return `Promise.resolve(...)`

2018-04-11 13:26 UTC, ingmarh approved these changes

2018-04-11 13:27 UTC, Raigen approved these changes

2018-04-11 13:59 UTC, merged