Chore: Provided function which runs after possible errors are occured
ePages-de/react-components pull request #42
Opened 2018-08-06 14:12 UTC by danilminibaev

Provided `OnError` function, to call extra actions in case of validation errors are there (both client-side and server-side).
E.g. to be able to toggle scroll into field with error

2018-08-08 07:01 UTC, ingmarh requested changes

2018-08-08 07:01 UTC, ingmarh commented on src/form/Form.jsx
> +      this.props.scrollIntoError && this.props.scrollIntoError(firstErrorKeyPath)
Since you have this in "defaultProps", you can omit the check.

2018-08-08 07:01 UTC, ingmarh commented on src/form/Form.jsx
> +    scrollIntoError: PropTypes.func
Instead of having a prop called "scrollIntoError", I suggest to have a more general "onError" prop (receiving the current errors as argument).

Scrolling (or other actions) could then be handled by using this prop.

2018-08-08 13:05 UTC, depoulo requested changes
just the typo

2018-08-08 13:05 UTC, depoulo commented on package.json
> +  "false": {},
wonder what that is 😬

2018-08-08 13:05 UTC, depoulo commented on test/form/Form.spec.jsx
> +    const otherPros = {
typo: otherProps

2018-08-09 11:34 UTC, danilminibaev commented on package.json
> +  "false": {},
🤔

2018-08-09 11:35 UTC, danilminibaev commented on test/form/Form.spec.jsx
> +    const otherPros = {
Will fix 👍

2018-08-09 13:01 UTC, depoulo submitted a review, later dismissed

2018-08-09 14:32 UTC, ingmarh submitted a review, later dismissed

2018-08-15 12:37 UTC, depoulo approved these changes

2018-08-15 12:43 UTC, merged